name: Deploy Jupyter Book

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 이거 추가

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install "jupyter-book<1.0" ghp-import

      - name: Build book
        run: |
          jupyter-book build .

      - name: Deploy
        run: |
          ghp-import -n -p -f _build/html 
